name: Node

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.18
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Yarn Cache Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Build
        run: |
          yarn
          yarn build
          yarn generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          personal_token: ${{ secrets.PAGE_PAT }}
          publish_dir: dist
